### ISSUE TITLE
Create initial models

### ISSUE THREAD

**Issue by aldnav** [channelfix/cshowdown-backend#1]
Base on your feature sets, identify the models that needs to be created (e.g., Entry, etc.,)

- [x] Create models
- [x] Commit the models and the model migration

**Comment by aldnav** [comment]
@emilarran status on this?

**Comment by emilarran** [comment]
currently working on it. am going to commit the models and model migration as soon as i finish, trying to finish tonight

**Comment by arnellebalane** [comment]
test comment, will delete shortly

**Comment by arnellebalane** [comment]
test comment, will delete shortly
